// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSRRifA6XDDnstYfXJwN36KU5oOSAb-I',
    appId: '1:773680822958:web:f73b6f8223ef600ae7cb3f',
    messagingSenderId: '773680822958',
    projectId: 'fcmpro-a8806',
    authDomain: 'fcmpro-a8806.firebaseapp.com',
    databaseURL: 'https://fcmpro-a8806.firebaseio.com',
    storageBucket: 'fcmpro-a8806.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGuBy09JExiOB6rQrCzoGymHx8NrWlXg',
    appId: '1:773680822958:android:40abd33afa23b4c7e7cb3f',
    messagingSenderId: '773680822958',
    projectId: 'fcmpro-a8806',
    databaseURL: 'https://fcmpro-a8806.firebaseio.com',
    storageBucket: 'fcmpro-a8806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQOsIX5Jz62mmIAhPv6qnHpOqjW9DH9oM',
    appId: '1:773680822958:ios:3ad8e14a04b13a4fe7cb3f',
    messagingSenderId: '773680822958',
    projectId: 'fcmpro-a8806',
    databaseURL: 'https://fcmpro-a8806.firebaseio.com',
    storageBucket: 'fcmpro-a8806.appspot.com',
    iosBundleId: 'com.example.todoapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQOsIX5Jz62mmIAhPv6qnHpOqjW9DH9oM',
    appId: '1:773680822958:ios:3ad8e14a04b13a4fe7cb3f',
    messagingSenderId: '773680822958',
    projectId: 'fcmpro-a8806',
    databaseURL: 'https://fcmpro-a8806.firebaseio.com',
    storageBucket: 'fcmpro-a8806.appspot.com',
    iosBundleId: 'com.example.todoapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSRRifA6XDDnstYfXJwN36KU5oOSAb-I',
    appId: '1:773680822958:web:6d0eea7a25159d17e7cb3f',
    messagingSenderId: '773680822958',
    projectId: 'fcmpro-a8806',
    authDomain: 'fcmpro-a8806.firebaseapp.com',
    databaseURL: 'https://fcmpro-a8806.firebaseio.com',
    storageBucket: 'fcmpro-a8806.appspot.com',
  );
}
